chaitin/MonkeyCode

- backend/internal/billing/repo/billing.go
> fix(record): 修复已删除用户列表没数据问题

- backend/internal/model/repo/model.go
> fix(model): 添加首个模型自动激活

- ui/src/pages/model/components/modelCard.tsx
- ui/src/pages/model/components/modelModal.tsx
> feat: 添加 show name

- backend/domain/model.go
- backend/internal/model/usecase/model.go
> feat(model): 支持配置自定义模型

- backend/internal/user/handler/v1/user.go
> feat: 缓存vsix包

- ui/src/api/types.ts
- ui/src/pages/admin/adminTable.tsx
- ui/src/pages/admin/index.tsx
- ui/src/pages/admin/loginHistory.tsx
- ui/src/pages/dashboard/components/pieCharts.tsx
- ui/src/pages/model/components/modelCard.tsx
- ui/src/pages/user-management/index.tsx
- 增加了管理员登录记录
- 修改了一些登录选项的显示名称
- 内置模型不能编辑
> 增加了管理员登录记录

- backend/db/migrate/schema.go
- backend/db/mutation.go
- backend/db/runtime/runtime.go
- backend/db/userloginhistory.go
- backend/db/userloginhistory/userloginhistory.go
- backend/db/userloginhistory/where.go
- backend/db/userloginhistory_create.go
- backend/db/userloginhistory_update.go
- backend/domain/user.go
- backend/ent/schema/userloginhistory.go
- backend/internal/user/repo/user.go
- backend/internal/user/usecase/user.go
- backend/migration/000008_alter_user_login_histories_table.up.sql
> feat(user): 登录历史增加hostname, client id字段

- ui/src/api/Model.ts
- ui/src/api/types.ts
- ui/src/components/user/index.tsx
- ui/src/pages/admin/loginHistory.tsx
- ui/src/pages/chat/index.tsx
- ui/src/pages/completion/index.tsx
- ui/src/pages/model/components/modelCard.tsx
- ui/src/pages/user-management/loginHistory.tsx
- ui/src/pages/user-management/memberManage.tsx
- ui/src/pages/user/chat/index.tsx
- ui/src/pages/user/completion/index.tsx
> 增加了成员登录记录 && 支持删除模型

- backend/docs/swagger.json
- backend/internal/model/repo/model.go
> feat(model): 模型删除检查

- backend/config/config.go
- backend/go.mod
- backend/internal/user/handler/v1/user.go
> feat: 下载限速

- backend/internal/proxy/repo/proxy.go
> fix: 修复行数计算问题

- backend/cmd/server/wire_gen.go
- backend/consts/user.go
- backend/docs/swagger.json
- backend/domain/billing.go
- backend/domain/dashboard.go
- backend/domain/oauth.go
- backend/domain/user.go
- backend/go.mod
- backend/go.sum
- backend/internal/billing/handler/http/v1/billing.go
- backend/internal/billing/repo/billing.go
- backend/internal/billing/usecase/billing.go
- backend/internal/middleware/active.go
- backend/internal/middleware/auth.go
- backend/internal/middleware/proxy.go
- backend/internal/model/handler/http/v1/model.go
- backend/internal/openai/handler/v1/v1.go
- backend/internal/user/handler/v1/dashboard.go
- backend/internal/user/handler/v1/record.go
- backend/internal/user/handler/v1/user.go
- backend/internal/user/repo/user.go
- backend/internal/user/usecase/user.go
- 增加用户登录来源
- 用户统计接口实现
- 用户使用记录接口实现
resolve: #59
> feat: 用户管理相关接口实现

- .github/workflows/backend-ci-cd.yml
- backend/Makefile
- backend/build/Dockerfile
- backend/cmd/server/main.go
- backend/cmd/server/wire.go
- backend/cmd/server/wire_gen.go
- backend/config/config.go
- backend/internal/provider.go
- backend/pkg/aes/aes.go
- backend/pkg/machine/machine.go
- backend/pkg/machine/machine_test.go
- backend/pkg/provider.go
- backend/pkg/report/report.go
- backend/pkg/report/types.go
- backend/pkg/version/version.go
> feat: 安装数据上报

- backend/internal/proxy/repo/proxy.go
> fix: 修复多次设置 input

- backend/config/config.go
- backend/docs/swagger.json
- backend/domain/oauth.go
- backend/domain/openai.go
- backend/domain/user.go
- backend/internal/openai/handler/v1/v1.go
- backend/internal/openai/usecase/openai.go
- backend/internal/user/handler/v1/user.go
- backend/internal/user/usecase/user.go
- backend/pkg/request/request.go
> feat: 通过请求获取 base url, 减少配置项

- backend/docs/swagger.json
- backend/internal/user/handler/v1/user.go
> feat: 登出接口实现

- backend/docs/swagger.json
- backend/internal/user/handler/v1/user.go
> feat: 管理员个人信息接口

- backend/cmd/server/wire.go
- backend/cmd/server/wire_gen.go
- backend/domain/report.go
- backend/internal/provider.go
- backend/internal/report/repo/report.go
- backend/internal/report/usecase/report.go
- backend/pkg/report/report.go
> feat: 数据上报

- ui/api-templates/http-client.ejs
- ui/src/api/Admin.ts
- ui/src/api/OpenAiv1.ts
- ui/src/api/User.ts
- ui/src/api/httpClient.ts
- ui/src/api/types.ts
- ui/src/components/header/index.tsx
- ui/src/context/index.tsx
- ui/src/hooks/context.ts
- ui/src/main.tsx
- ui/src/pages/auth/index.tsx
- ui/src/pages/invite/index.tsx
- ui/src/pages/login/index.tsx
- ui/src/pages/user/setting/index.tsx
- ui/src/router.tsx
> 添加退出登录，修复闪跳问题

- backend/internal/user/repo/user.go
> feat: 头像自动更新

- backend/internal/extension/usecase/extension.go
- backend/pkg/vsix/vsix.go
> feat: 统一插件与服务端的版本号

- backend/internal/user/usecase/user.go
> feat: 允许自动注册

- backend/internal/report/usecase/report.go
> chore: 上报时间调整

- backend/cmd/server/main.go
- backend/cmd/server/wire.go
- backend/cmd/server/wire_gen.go
- backend/domain/extension.go
- backend/internal/extension/usecase/extension.go
> fix: 修复插件下载失败

- backend/config/config.go
- backend/internal/openai/handler/v1/v1.go
- backend/internal/user/handler/v1/user.go
- backend/internal/user/usecase/user.go
- backend/pkg/request/request.go
> fix: 修复插件下载端口不对

- ui/src/main.tsx
> fix: 模型激活问题

- ui/src/pages/chat/index.tsx
- ui/src/pages/user/chat/index.tsx
> fix: 对话记录翻页问题

- backend/config/config.go
> fix: 修复baseurl端口问题

- backend/internal/user/repo/user.go
> fix: 修复用户更新不生效

- ui/src/main.tsx
- ui/vite.config.ts
> fix: MonacoEnvironment warning

- backend/domain/user.go
- backend/errcode/errcode.go
- backend/errcode/locale.zh.toml
- backend/internal/user/repo/user.go
- backend/internal/user/usecase/user.go
> fix: 用户锁定判断

- ui/api-templates/http-client.ejs
- ui/src/api/httpClient.ts
- ui/src/components/header/index.tsx
- ui/src/main.tsx
- ui/src/pages/login/index.tsx
- ui/src/router.tsx
> feat: 用户登录和管理员登录合一起

- backend/internal/model/usecase/model.go
> chore: 百智云模型列表参数修正

- backend/internal/model/usecase/model.go
> fix(model): 兼容硅基流动 sub_type

- backend/cmd/server/wire_gen.go
- backend/config/config.go
- backend/db/migrate/schema.go
- backend/db/mutation.go
- backend/db/runtime/runtime.go
- backend/db/setting.go
- backend/db/setting/setting.go
- backend/db/setting/where.go
- backend/db/setting_create.go
- backend/db/setting_update.go
- backend/docs/swagger.json
- backend/domain/user.go
- backend/ent/schema/setting.go
- backend/ent/types/types.go
- backend/internal/openai/handler/v1/v1.go
- backend/internal/user/handler/v1/user.go
- backend/internal/user/repo/user.go
- backend/internal/user/usecase/user.go
- backend/migration/000013_add_base_url_for_settings_table.down.sql
- backend/migration/000013_add_base_url_for_settings_table.up.sql
- ui/nginx.conf
> feat: 支持配置前置代理

- backend/db/migrate/schema.go
- backend/db/model/where.go
- backend/db/model_create.go
- backend/db/model_update.go
- backend/db/mutation.go
- backend/ent/schema/model.go
- ui/src/pages/model/components/modelModal.tsx
> fix(model): 修复模型配置api key必填问题, 修复高级配置类型错误问题

- ui/src/pages/dashboard/components/memberInfo.tsx
> feat: 优化热力图组件展示

- .github/workflows/backend-ci-cd.yml
- .gitignore
- backend/build/Dockerfile
- backend/cmd/server/main.go
- backend/internal/openai/handler/v1/v1.go
- backend/internal/user/handler/v1/user.go
> feat: 嵌入vsix

- .github/workflows/backend-ci-cd.yml
> fix: 修复ci下载VSIX

- .gitattributes
- .github/workflows/backend-ci-cd.yml
- .gitignore
- backend/assets/vsix/monkeycode-1.7.0-alpha.vsix
> feat: 用lfs上传vsix文件

- .github/workflows/backend-ci-cd.yml
> feat: 下载 sgp

- .github/workflows/backend-ci-cd.yml
> feat: 打开子模块

- backend/Makefile
- backend/doc.go
- backend/domain/security.go
- backend/internal/security/repo/security.go
> feat: 扫描详情增加代码原文

- .github/workflows/backend-ci-cd.yml
- backend/build/Dockerfile.scanner
> feat: sgp 多架构下载

- .github/workflows/backend-ci-cd.yml
> fix: 修复目录未创建

- backend/pkg/store/entdb.go
> fix: 修复postgres vector插件迁移

- .gitignore
- backend/consts/security.go
- backend/domain/security.go
- backend/internal/proxy/usecase/proxy.go
- backend/internal/scanner/handler/http/v1/scanner.go
> fix: 修复c/c++代码扫描无效问题

- .github/workflows/backend-ci-cd.yml
> chore: 修改vsix,sgp的下载地址

- backend/internal/socket/handler/socket.go
- backend/internal/workspace/usecase/workspace.go
修复了在高并发环境下创建工作区时出现的重复键约束冲突错误
backend/internal/workspace/usecase/workspace.go - 工作区业务逻辑层
backend/internal/socket/handler/socket.go - WebSocket 事件处理层
关闭 #
> fix: resolve workspace creation race condition causing duplicate key constraint violations

- .github/workflows/backend-ci-cd.yml
> feat: 关闭ci中的lfs

- .github/workflows/backend-ci-cd.yml
> fix: 创建一个空的swagger.json, 保证build成功

- ui/src/pages/memberManage/memberManage.tsx
> feat: 成员管理列表支持用户名和邮箱的模糊搜索

- backend/errcode/errcode.go
- backend/errcode/locale.en.toml
- backend/errcode/locale.zh.toml
- backend/internal/user/repo/user.go
> feat: 优化用户登录注册提示

- ui/src/pages/memberManage/index.tsx
> feat: 支持 oauth 配置

- backend/config/config.go
- backend/internal/user/repo/user.go
> feat: 取消用户限制配置参数

- backend/internal/openai/usecase/openai.go
> feat: 改变模型配置下发名字

- .gitignore
> fix: 修复ai员工跳过逻辑报错

- ui/src/pages/chat/index.tsx
> fix: work_mode 不匹配问题
